### ISSUE TITLE
MELLIL and BIBRUREK

### ISSUE THREAD

**Issue by johnbent** [tekinged/missing#100]
MELLIL and BIBRUREK created by palau371@gmail.com on 2018-05-08 10:31:39

**Comment by johnbent** [comment]
palau371@gmail.com replied, <br><br><p>is therre any difference between them? which of them is more common, than other?&nbsp;</p><p><br></p><p>thanks!</p>

**Comment by johnbent** [comment]
mngiruchelbad@gmail.com replied, <br><br>Mellil is used more towards plants.

**Comment by johnbent** [comment]
jlukesemiwo@gmail.com replied, <br><br>Mellil, apparently, is used only for yellow leaves or the yellow in grass
skirt, whereas bibrurk is yellow for anything..

**Comment by s-o-u-a-n-g** [comment]
Fun fact! My sister had a kitten named Mellil! She was the color of meuilech el brak and mellil el llel a bobai. 

It’s also a word in one of my favorite songs 

“… muu er a mellil er a cheungel a kerrekar..”
The song is called SIM about the leaves changing. 

souang
