### ISSUE TITLE
sekodechelakl

### ISSUE THREAD

**Issue by johnbent** [tekinged/missing#116]
sekodechelakl created by palau371@gmail.com on 2017-05-02 15:03:19

**Comment by johnbent** [comment]
palau371@gmail.com replied, <br><br><p>Bible has it, but our DB doesn't have it yet... what is the best english translation for this word?</p>

**Comment by johnbent** [comment]
johnbent@gmail.com replied, <br><br>I assume this is the passage:

Ng diak di loumerreder er ngii, e le bekongesengasech a rengul, ma ka le
sekengim er a mesisiich el ilumel, ma lechub e le sekodechelakl ma lechub e
le ngemokel a udoud.

Here's the translation:

He must not be arrogant or quick-tempered or a drunkard or violent or
greedy for gain,

Looks like it must be violent.  E kemiu a rechad er a Belau?

**Comment by johnbent** [comment]
jlukesemiwo@gmail.com replied, <br><br>I initially thought of "violent" but replied with "bellicose." What do you
think? Same difference? :)

**Comment by johnbent** [comment]
mngiruchelbad@gmail.com replied, <br><br>Combative: argumentative

**Comment by johnbent** [comment]
toninewton54@yahoo.com replied, <br><br>Â Sekodechelakl- prone to fighting. Â Fiesty

Emails/html
|
|  --- Write ABOVE THIS LINE to reply ---
Aleksandr Kuznetsov posted a new comment on sekodechelakl :
 Bible has it, but our DB doesn't have it yet... what is the best english translation for this word? View this on DebugleStop receiving email notifications about this item.  |

  |

**Comment by johnbent** [comment]
palau371@gmail.com replied, <br><br><p>My friends, i think we need some phrase examples for that word.</p><p>Kmal mesaul!</p>

**Comment by johnbent** [comment]
mngiruchelbad@gmail.com replied, <br><br>A Ulang a meral sekodechelakl, ng kuk milcheliang el di oumondai. Ulang is
so fiesty, she's back at it arguing again. ðŸ˜Š

**Comment by johnbent** [comment]
palau371@gmail.com replied, <br><br><p>wow! i think i don't know what's MILCHELIANG)))</p>

**Comment by johnbent** [comment]
mngiruchelbad@gmail.com replied, <br><br>Oh milcheliang 're start' root word 'omuchel'

**Comment by johnbent** [comment]
johnbent@gmail.com replied, <br><br>Aleks,

Does this mean that v.t.inch. forms have past tense forms?  That's
interesting.  Did we know that?

**Comment by johnbent** [comment]
palau371@gmail.com replied, <br><br><p>John, we didn't know that. either Josephs. we need a special discussion here about it</p>

**Comment by s-o-u-a-n-g** [comment]
Excellent sentence e Ulang! Ke kuk milecheliang el omeldukl a tekoi el dimlak el uldimukl er a chelsel tia el blai. 

souang
