### ISSUE TITLE
ringko, chidudes

### ISSUE THREAD

**Issue by johnbent** [tekinged/missing#117]
ringko, chidudes created by palau371@gmail.com on 2017-03-06 04:59:34

**Comment by johnbent** [comment]
palau371@gmail.com replied, <br><br><p>mr. Masaharu used these words in one of his books. why haven't we added them yet? do people use it?</p><p>w ringko n. phosphate</p><p>w chidudes n. bauxite</p><p><br></p>

**Comment by johnbent** [comment]
palau371@gmail.com replied, <br><br><p>(for John) if you gonna add them, so:</p><p>l chidedesall chidudes</p>

**Comment by johnbent** [comment]
johnbent@gmail.com replied, <br><br><p>Can anyone please confirm ringko and chidudes please?</p>

**Comment by johnbent** [comment]
belausim@gmail.com replied, <br><br>ringko japanese word, chidudes is palauan word..don't know the english word

**Comment by johnbent** [comment]
palau371@gmail.com replied, <br><br><p>here it is</p>

**Comment by johnbent** [comment]
mngiruchelbad@gmail.com replied, <br><br><p>bauxite for chidudes.</p>

**Comment by Gnalu** [comment]
Ringo-apple
Phosphate-rinsan

**Comment by s-o-u-a-n-g** [comment]
I replied maybe to an earlier thread on this same thing. 
Ringko from Japanese for Phosphate. 
Chidudes is Palauan word for the red jagged rock in the ked mined as bauxite by Japanese to make aluminum. 

souang
