### ISSUE TITLE
BECHES EL OCHAIS

### ISSUE THREAD

**Issue by johnbent** [tekinged/missing#119]
BECHES EL OCHAIS created by johnbent@gmail.com on 2017-03-05 10:34:22

**Comment by johnbent** [comment]
johnbent@gmail.com replied, <br><br><p>'BECHES EL OCHAIS' is an expression that means 'tell the truth.' &nbsp;Anyone confirm please?</p>

**Comment by johnbent** [comment]
jlukesemiwo@gmail.com replied, <br><br>Should be ouchais.

And yes, however, it's not necessarily just telling the truth vs. lying.
It could just be about being frank, direct...essentially, no beating around
the bush.

Ex. Bai di beches el ouchais el kmo ng chetim el mong e lak ko bong e
mouuchel ra rengum. Be honest and say you don't want to go instead of going
and then regretting it.

Ng bai soak a di beches el ouchais er ngak ra bai mongeteket er ngii.  I
want you to be direct with me instead of prolonging it.

**Comment by johnbent** [comment]
johnbent@gmail.com replied, <br><br>Awesome sentences and revision to the meaning.  Thanks.

**Comment by johnbent** [comment]
belausim@gmail.com replied, <br><br>Beches el ou chais, ?

**Comment by Gnalu** [comment]
Isn’t ‘beches el ouchais’ simply straight up, upfront?
