### ISSUE TITLE
ngedibek

### ISSUE THREAD

**Issue by johnbent** [tekinged/missing#124]
ngedibek created by mngiruchelbad@gmail.com on 2017-02-14 13:54:52

**Comment by johnbent** [comment]
johnbent@gmail.com replied, <br><br><p>Sometimes debugle is weird. &nbsp;Looks like this new thread wasn't emailed out to all of us. &nbsp;So I'm just commenting in order to notify everyone. &nbsp;The original post from Ulang is,&nbsp;</p><p>"ngedibek: alii ke mo era 'ngedibek': shunned maybe?"</p>

**Comment by s-o-u-a-n-g** [comment]
Sounds right. To be flicked away, turned away. Not as endearing as “nguu el mo er a ngetecheuid”. 

Chediul! Lak molekoi el uaisei e ke di kau el ngoikau el mo er a ngedibek. 

souang

**Comment by johnbent** [comment]
AUTOPARSE
w ngedibek v.s. (person) shunned or avoided (by others).
e Chediul! Lak molekoi el uaisei e ke di kau el ngoikau el mo er a ngedibek. --Uh oh! Don't speak like that or you'll make yourself shunned.

**Comment by johnbent** [comment]
@smith-371 @ChrisPerrette , can you both approve this autoparse if it looks good to you. We have confirmation from @s-o-u-a-n-g and @Gnalu so we just need to check the autoparse.

**Comment by ChrisPerrette** [comment]
Something seems off to me. I'm sure that _ngedibek_ means what you say, but looking at the grammar of the example sentence, it seems to be a noun rather than a state verb. It might even be a possessed form in the first person. Is the last syllable -_ek_ stressed, and if so, is there a _ngedibel?_ Either way it seems like a noun that means something like ‘disfavor’ or ‘disapproval’ or perhaps ‘banishment.’

**Comment by Gnalu** [comment]
Ngedibek is derived from olibek, melibek.

**Comment by ChrisPerrette** [comment]
I wondered if it had something to do with _melibek_. It says it means to kick away or sweep away. I can’t think of an English noun that matches such a situation.

If it said _mo ngedibek_, a state verb would make sense, but with the _er a_ I can’t see it not as a noun, and almost as a place, perhaps conceptually.

**Comment by Gnalu** [comment]
Alii, Kemo era ngedibek!

Hello, ima kick you to the curb! Kinda that sense….

**Comment by ChrisPerrette** [comment]
That makes sense.

**Comment by johnbent** [comment]
How is it pronounced? I'm guessing it is pronounced as 'nge-di-be-ka' which means (I believe) that it is not n.poss.s3).

Could it be v.erg.?

mysql> select pal,pos from all_words3 where pal rlike 'k\\b' and pos not like 'n.poss.s3' and pos not like 'v.pf.1s' and pos like 'v.erg.';
+--------------+--------+
| pal          | pos    |
+--------------+--------+
| obok         | v.erg. |
| mechilekelek | v.erg. |
| obutek       | v.erg. |
| betik        | v.erg. |
| mechimkomk   | v.erg. |
| mechituuk    | v.erg. |
| medekodek    | v.erg. |
| mederubek    | v.erg. |
| medibek      | v.erg. |
| medirek      | v.erg. |
| medirek      | v.erg. |
| medolk       | v.erg. |
| metamk       | v.erg. |
| modak        | v.erg. |
| modik        | v.erg. |
| moiubek      | v.erg. |
| mokeek       | v.erg. |
| mokiik       | v.erg. |
| mongaok      | v.erg. |
| mongeasek    | v.erg. |
| morekorek    | v.erg. |
| moriik       | v.erg. |
| mosebek      | v.erg. |
| moskosk      | v.erg. |
| motak        | v.erg. |
| moturek      | v.erg. |
| mukramek     | v.erg. |
| mungamk      | v.erg. |
| mutok        | v.erg. |
| mututk       | v.erg. |
| obadek       | v.erg. |
| obadk        | v.erg. |
| obkobk       | v.erg. |
| obodk        | v.erg. |
| oboik        | v.erg. |
| oburek       | v.erg. |
| mederdirk    | v.erg. |
| metik        | v.erg. |
| obak         | v.erg. |
| obengkangk   | v.erg. |
| mongkongk    | v.erg. |
| metark       | v.erg. |
| metabek      | v.erg. |
| medebedebek  | v.erg. |
| medekedek    | v.erg. |
| meteketek    | v.erg. |
| mesekosek    | v.erg. |
| medemedemek  | v.erg. |
| mengiik      | v.erg. |
| medik        | v.erg. |
| metuk        | v.erg. |
| metukouk     | v.erg. |
| metutk       | v.erg. |
| mechetikaik  | v.erg. |
| mekiok       | v.erg. |
| mekuk        | v.erg. |
| merebek      | v.erg. |
| meriik       | v.erg. |
| mesamk       | v.erg. |
| mesebek      | v.erg. |
| mesilek      | v.erg. |
| mesuk        | v.erg. |
| mesumk       | v.erg. |
| modekedek    | v.erg. |
| modirekorek  | v.erg. |
| moterebek    | v.erg. |
| obekebek     | v.erg. |
| muklatk      | v.erg. |
| obitelek     | v.erg. |
| obkuuk       | v.erg. |
| moreek       | v.erg. |
| morumk       | v.erg. |
| mesiik       | v.erg. |
| mouak        | v.erg. |
| oberk        | v.erg. |
| mongemek     | v.erg. |
| medibuk      | v.erg. |
| mengabek     | v.erg. |
| moalek       | v.erg. |
+--------------+--------+
79 rows in set (0.13 sec)

mysql>

**Comment by Gnalu** [comment]
Ng-Ed-ibk

**Comment by ChrisPerrette** [comment]
There is also the n.poss.3s _dbekel_. Is this possibly a possessed form of _ngedibek?_

**Comment by johnbent** [comment]
> There is also the n.poss.3s _dbekel_. Is this possibly a possessed form of _ngedibek?_

But that would mean that NGEDIBEK is an unpossessed noun and that doesn't fit the examples we have.

**Comment by Gnalu** [comment]
A debkel a Ulang el mo diak el teloi er kid a ko er a kmal oberaod meirei.

Banning/shunning Ulang to not be part of us seems a bit tall order.

**Comment by johnbent** [comment]
Awesome. So 'debkel' seems clearly to be 'n.poss.3s' and from the same root word as ngedibek.

@Gnalu , can you offer more sentences using more different forms of this word? Is there something like ngildibek or something? And you can use 'debkem' to mean 'the shunning of you'?

**Comment by Gnalu** [comment]
A Ulang a mlodibek er a er a rael el ruebet er a dobu. Ulang got shoved
from the road into the ditch.

Olibekem-your banishment. Ulang, ngdi mle kau locheuir olibkem er a
klekool. Ulang, it’s your fault you got kicked out of the game.

**Comment by smith-371** [comment]
NGEDIBEK seems to be a noun, agree with @ChrisPerrette . but I am not familiar with this word.

**Comment by johnbent** [comment]
@smith-371 and @ChrisPerrette , we cannot let the perfect be the enemy of the good. We have 140 open issues because we have not been able to fully convince ourselves that we understand them perfectly. But tekinged would be better with imperfect inclusions of these identified words than excluding them altogether.

**Comment by johnbent** [comment]
AUTOPARSE
w ngedibek n. a person who is shunned, avoided,excluded (by others). --debkel n.poss.3s
e Chediul! Lak molekoi el uaisei e ke di kau el ngoikau el mo er a ngedibek. --Uh oh! Don't speak like that or you'll make yourself shunned.
e A debkel a Ulang el mo diak el teloi er kid a ko er a kmal oberaod meirei. --Excluding Ulang seems excessive.

**Comment by ChrisPerrette** [comment]
Looks good

**Comment by johnbent** [comment]
> Looks good

Cool. Can you thumbs up please since the autoparse script refuses to run unless there are two thumbs ups.

**Comment by ChrisPerrette** [comment]
I can't give a react. For some reason, it sometimes does not display any the option sometimes.

**Comment by johnbent** [comment]
If you are the first one to give it a react, then you have to give it a react in a different place. On the right somewhere.
________________________________

**Comment by ChrisPerrette** [comment]
![Screenshot_20221028-204239](https://user-images.githubusercontent.com/116015127/198753980-76fc717f-1b23-48a3-ad9b-bbb66dc4a6ad.png)

**Comment by johnbent** [comment]
@ChrisPerrette , now that I thumbs it, do you see it?

**Comment by ChrisPerrette** [comment]
Yes, I gave it a thumbs up.

**Comment by johnbent** [comment]
@ChrisPerrette , for future reference, there are two ways to add a thumbs-up:
1. If no-one else has yet added a thumbs-up, click on the smiley face in the upper right of the comment
2. if someone else has already added a thumbs-up, click on the thumbs-up in the bottom left of the comment to add another
<img width="976" alt="image" src="https://user-images.githubusercontent.com/2047294/199540847-4baff390-75b5-4efa-ad51-68891b25a5d5.png">

The above image is what you see when you click on the smiley face in the upper right corner

@smith-371 , can you please give a thumbs up also to the autoparse so we can close this one?

**Comment by johnbent** [comment]
![40691.1667955145.png](https://tekinged.com/tmp/screenshots/40691.1667955145.png)

**Comment by johnbent** [comment]
AUTOPARSE successfully AUTOPARSED.<br>@johnbent, please check the website (and any screenshots above).<br>If everything looks good, please close this Issue.
