### ISSUE TITLE
Omnger: constantly telling someone of the same task over because it doesn't get done.

### ISSUE THREAD

**Issue by johnbent** [tekinged/missing#127]
Omnger: constantly telling someone of the same task over because it doesn't get done. created by mngiruchelbad@gmail.com on 2017-01-25 14:03:44

**Comment by johnbent** [comment]
mngiruchelbad@gmail.com replied, <br><br><p>Ulang, ak mesikang el omnger er kau era omelchelbem!</p><p>Ulang, i am tired of telling you to do your shower!</p>

**Comment by johnbent** [comment]
palau371@gmail.com replied, <br><br><p>&gt;&nbsp;<span>omelechelbem</span></p><p><span>we don't have it too</span></p>

**Comment by johnbent** [comment]
mngiruchelbad@gmail.com replied, <br><br><p>Melecholb related to omelchelbem</p>

**Comment by s-o-u-a-n-g** [comment]
I concur. 

souang
