### ISSUE TITLE
OL'AU

### ISSUE THREAD

**Issue by johnbent** [tekinged/missing#14]
From https://campaignbrief.com/the-palau-legacy-project-launches-olau-palau-a-world-first-tourism-initiative-via-host-havas/ it says,
"In the local Palauan language, “ol’au” is a way of calling out to a friend to invite them into your space. "

So what the heck is OL'AU? What word(s) does this come from?

**Comment by johnbent** [comment]
Oh, it must be [OLECHAU](https://tekinged.com/?lookup=olechau&direction=pe).
So, is OL'AU pronounced the same as OLECHAU or is it a different form?

**Comment by Lukes-Imeyuns** [comment]
Looks like they're being creative...

The definition they used is definitely that of OLECHAU.

I do hear people saying it in both ways - olechau where you can hear the
almost silent "e" or olchau.

**Comment by Gnalu** [comment]
It’s a new apostrophed spelling; I have people suggest to me to change my
dad’s name to Ngiru’elbad easier for non Belauan speaking people not to get
confused with ‘ch’ rolling with the next letter ‘e’.

**Comment by s-o-u-a-n-g** [comment]
‘Okina appropriation. Foreigners in the committee not consulting with locals. I contacted the author of the press re-release from South China Post to correct their explanation. Thankfully they did. 

souang

**Comment by johnbent** [comment]
Hey that’s awesome @s-o-u-a-n-g! Can you paste the link to the corrected article please?

Also, they define it as, “ a way of calling out to a friend to invite them into your space,” which makes it sound like someone sees their friend walking by and they yell “olechau” at them. But that’s incorrect. Instead they maybe beckon them with a hand gesture or something. And the name of the action is olechau. Olechau is not the sound articulated to call someone over which is how they incorrectly describe it. 

Thanks all!!!

**Comment by s-o-u-a-n-g** [comment]
Link to my OP tweet 

https://twitter.com/souang/status/1514097024630607877?s=21&t=QVeo78DOX8S7Wvcnv2jAxQ

Link to article with correction. They didn’t acknowledge the mistake nor credit the correction. 

https://www.scmp.com/magazines/post-magazine/travel/article/3174011/where-sustainable-tourism-rewarded-special-cultural

souang
