### ISSUE TITLE
japanese word KAZE in Palauan

### ISSUE THREAD

**Issue by johnbent** [tekinged/missing#142]
japanese word KAZE in Palauan created by palau371@gmail.com on 2016-12-23 15:14:51

**Comment by johnbent** [comment]
palau371@gmail.com replied, <br><br><p>I've encountered in a medical booklet the next:</p><p>Bo blechoel melatech er a telemall e bilii er a kaze.</p><p>what is KAZE?</p>

**Comment by johnbent** [comment]
palau371@gmail.com replied, <br><br><p>In Japanese KAZE means "wind" (i think everybody heard about kamikaze, lit. "holly wind"), another meaning of KAZE in Japanese is "cold" (= rakt el tereter). but none of two meanings fits the example above...</p>

**Comment by johnbent** [comment]
mngiruchelbad@gmail.com replied, <br><br><p>Gauze bandage is kaze.</p>

**Comment by johnbent** [comment]
mngiruchelbad@gmail.com replied, <br><br><p>It's not Japanese, it's English 'gauze'&nbsp;</p>

**Comment by johnbent** [comment]
johnbent@gmail.com replied, <br><br><p>Aleks, can you send me the medical booklet please? Or do we already have it?</p>

**Comment by s-o-u-a-n-g** [comment]
Correct. Kaze is En for gauze. 

souang
