### ISSUE TITLE
Word for "ticket"

### ISSUE THREAD

**Issue by johnbent** [tekinged/missing#145]
Word for "ticket" created by palau371@gmail.com on 2016-12-17 23:23:42

**Comment by johnbent** [comment]
palau371@gmail.com replied, <br><br><p>is there any palauan word for TICKET? i mean ticket for boat/plane/train/cinema etc. now we have none in DB</p>

**Comment by johnbent** [comment]
mngiruchelbad@gmail.com replied, <br><br><p>My dad used Japanese word 'kippu' , anyone else heard this word growing up or not?</p>

**Comment by johnbent** [comment]
johnbent@gmail.com replied, <br><br><p>I wouldn't expect there to be a Palauan word for ticket since there were no tickets pre-Japanese days.</p>

**Comment by johnbent** [comment]
palau371@gmail.com replied, <br><br><p>I meant something like "babier er a siseball el mo er a", or Japanese borrowing</p>

**Comment by johnbent** [comment]
johnbent@gmail.com replied, <br><br><p>I added it and marked it as archaic.</p>

**Comment by johnbent** [comment]
johnbent@gmail.com replied, <br><br><p>Aleks, I think they mostly just say ticket.</p>

**Comment by s-o-u-a-n-g** [comment]
Archaic marking is good. Some words we adopted the English word and dropped the Japanese word. Like Ticket instead of Kippu. 
Sometimes we keep both like KOMI (Jp) and BESBAS (Sp basura). 

souang
