### ISSUE TITLE
obuu

### ISSUE THREAD

**Issue by johnbent** [tekinged/missing#146]
obuu created by jimgeselbracht@yahoo.com on 2016-12-17 12:07:08

**Comment by johnbent** [comment]
jimgeselbracht@yahoo.com replied, <br><br><p>Missing word: &nbsp;obuu (crash), ulebuu (crashed), lobuu (it crashes). &nbsp;"lobuu a daob" = ocean waves crash</p><p>In the song "adidil era rokungatsu" is the phrase "dibe obuu me lomedebodes"</p><p>I see that obuu is v.erg of omuu and means "explode, break open, etc." &nbsp;Is this the same word with a slightly different meaning?</p>

**Comment by johnbent** [comment]
johnbent@gmail.com replied, <br><br><p>Jim, we have obuu already twice in the dictionary. &nbsp;Once as the ergative (passive) of explode/break and once as a noun meaning blister. &nbsp;Have you seen it in a different context somewhere?</p>

**Comment by johnbent** [comment]
johnbent@gmail.com replied, <br><br><p>I added crash as another meaning of omuu.</p>

**Comment by johnbent** [comment]
mngiruchelbad@gmail.com replied, <br><br><p>Langsu teru el rubaks</p>

**Comment by johnbent** [comment]
jimgeselbracht@yahoo.com replied, <br><br>Well, in the two examples I gave, but probably this is a variation of "break": Â lobuu a daob (ocean waves crash) [from Mototoi Hanarete]. Â In Adidil era Rokungatsu: Â "Dibe obuu me lomedebodes a kuk lotkid ra irechar" (when the sea is agitated and the waves are crashing, it almost reminds us of our past) -- in that one the "daob" part of obuu is implied, I think.

    On Saturday, December 17, 2016 11:17 AM, John Bent (Debugle) <notifications@debugle.com> wrote:


  Emails/html
|
|  --- Write ABOVE THIS LINE to reply ---
John Bent posted a new comment on obuu :
 Jim, we have obuu already twice in the dictionary. Â Once as the ergative (passive) of explode/break and once as a noun meaning blister. Â Have you seen it in a different context somewhere? View this on DebugleStop receiving email notifications about this item.  |

  |

**Comment by johnbent** [comment]
mngiruchelbad@gmail.com replied, <br><br>Obuu era kederang: omdebodes/meluil: when it is rolling towards the shore
when it hits the shore its obuu.

**Comment by s-o-u-a-n-g** [comment]
Obuu - exploding, crashing (as in waves), breaking (only for round solid objects such as skull, coconut)

Omuu - the act of exploding. Omuu a Hanabi. Exploding the firecrackers. 

Kau ke omuu a hanabi? 
Ochoi ng mla obuu. 



souang
