### ISSUE TITLE
-kid as a suffix

### ISSUE THREAD

**Issue by johnbent** [tekinged/missing#172]
The Josephs dictionary has _kid_ as a full word used for emphasis:
![image](https://user-images.githubusercontent.com/2047294/196201400-dbf232df-b2fa-448a-8231-a756629b9e70.png)

But, Palauans almost always write it by appending it to words:

- Ngdi tiaikid a uchul e ak mlei!
- Me ngulemuchel er tiaikid el taem
- "Choi. Ochoi, tiaikid a kulekoi er ngii," ng ulenger a debar.
- Chelsel tiakid el taem el blok rereuchel
- A Rengedel a eanged a ua tiakid
- Aikaikid el okesiu er a klisichel a Tngakireng er a klengar er a rechad
- Aikaikid me a lousbech el chachedecheduch.
- Aikaikid el chutem a chetemel a bedengel a chad.

Thoughts about adding it as a suffix perhaps in addition to having it as a full word? Or getting rid of the full word version and just making it a suffix?

**Comment by Gnalu** [comment]
Suffix as in other usage like so:
Ekid tiang el Mla mo kaodengei.
Me tiakid el Mla mo uaisei.
 My thoughts…

**Comment by ChrisPerrette** [comment]
The fact that <i>kid</i> often receives the <i>i</i>- prefix makes me wonder if the word should be separate. <i>E</i>.<i>g</i>., <i>tiaikid</i> vs. <i>tia ikid</i>

**Comment by Gnalu** [comment]
I’m not the expert but Belauans like to emphasize on some letters per se
‘Tiaikid ‘ch!’-this is it!  And in someone who’s not so enthusiastic would
 manage a simple ‘tiaikid or tiakid.’

I’m referring to Spanish where they roll their R’s when one would just say
it without rolling their R. Maybe I’m pulling from thin air… 😁

Langsu,
Ulang

**Comment by johnbent** [comment]
Closing. Discussed in #282 and #37
