### ISSUE TITLE
IMINGS

### ISSUE THREAD

**Issue by johnbent** [tekinged/missing#20]
All,

info@tekinged.com received this email today:

================================
I was reading a passage of the New Testament in Palauan and came upon a word whose definition I could not find. The word is “imings,” which is apparently part of a phrase like “imings a medal.” The passage from which I read this says, “...ak bai mengull ra Demak, e kemiu a imings a medemiu er ngak.” This, as you probably know, means something like, “...I honor my Father, but you dishonor me.” There are other instances of this word I have found, too. I could not find the word listed in [tekinged.com](http://tekinged.com/), my New Palauan-English Dictionary, or the A Klechibelau Palauan Dictionary. I was wondering if you were familiar with this word or phrase and if you had a definition for it. If you do have it, could you add it to your website.
================================

Anyone know this word? Charl and I aren't familiar with it.

**Comment by Gnalu** [comment]
Imings is overlooked, ignore, bypass.

**Comment by Lukes-Imeyuns** [comment]
Yeah, look the other way, avoid eye contact as a way of ignoring the other
person. I don't know though what the root word would be...

**Comment by Gnalu** [comment]
I do believe it’s ‘imiu’or ‘chimiu’.
Ak chulechau rkau eh Kitalong er chelii er a bdelul a chang eng ko er a di
imiu osengem, kulmes el mor?  I was trying to get your attention but wasn’t
successful, where were you looking at?

Ulang, ke cheuiko, ngdiak mesa tilechang el besbas el nga er a mekesokes,
ngmla mo telal chomiiu er ngii el mong e mei!?!? Ulang, can’t you see the
trash on the ground that you have passed it by back and forth?!?

**Comment by johnbent** [comment]
Weird. Lukes' sister just emailed me about this same word. Here's what she said:

imings.. 
imings a medal... olechib osengel malechub mekngit osengel bedul a chad. 
i think olechib osengel is more appropriate.. but then again, maybe it depends on how you use it?? 
sulang.. 

I asked her to join us here! :)

**Comment by smith-371** [comment]
i can't find IMINGS in this bible translation https://live.bible.is/bible/paupal/mat/3

**Comment by ChrisPerrette** [comment]
I have an older New Testament than the commonly used one. I can't really seem to find much information about it, though. I am slowly making my way through copying it over to my computer.

**Comment by johnbent** [comment]
AUTOPARSE
w imings v.i. overlook, ignore, avoid eye contact, look away.
