### ISSUE TITLE
omengib

### ISSUE THREAD

**Issue by johnbent** [tekinged/missing#239]
omengib created by jimgeselbracht@yahoo.com on 2017-05-04 11:01:09

**Comment by johnbent** [comment]
jimgeselbracht@yahoo.com replied, <br><br>I believe this means "ripen, bloom". Â It is used in two examples currently in tekinged: Â "Ser a bo le belsechel omengib el rodech" translated as "When the season for fruit drew near". Â Also used in the song "Tal Becheleleu el Bung" -- Â "ng bai derengul a diak a rengul momengib era sakura", which I translate as "lucky is the one without feelings for the bloom of the flower"

**Comment by johnbent** [comment]
toninewton54@yahoo.com replied, <br><br>omengib..picking as of fruit & flower. " when the season for fruit is drew near. Â sel bol temel omengib el rodech"
Harvest time. Â mla kirel mengai.Â 
Tia Becheleleu el Bung..white for purity. Â This song is about someone who doesn't give a damn for the girl, but just one to be the her first man. Â AkumdasuEmails/html
|
|  --- Write ABOVE THIS LINE to reply ---
Jim Geselbracht posted a new comment on omengib :
 I believe this means "ripen, bloom". Â It is used in two examples currently in tekinged: Â "Ser a bo le belsechel omengib el rodech" translated as "When the season for fruit drew near". Â Also used in the song "Tal Becheleleu el Bung" -- Â "ng bai derengul a diak a rengul momengib era sakura", which I translate as "lucky is the one without feelings for the bloom of the flower" View this on DebugleStop receiving email notifications about this item.  |

  |

**Comment by johnbent** [comment]
johnbent@gmail.com replied, <br><br>http://tekinged.com/aw/m/mengib.htm

I think adding an o- prefix in front of verbs often makes an action noun. Aleks, confirm?  So omengib is like the act of plucking.

**Comment by johnbent** [comment]
jimgeselbracht@yahoo.com replied, <br><br>Thanks Antonia. Â And I thought that song was just about a flower! :-) Â Thanks John for pointing out mengib. Â I should have looked for that. Â it should be written mo mengib in the case of the song. Â But the bible verses may support the form "omengib"

    On Thursday, May 4, 2017 6:16 PM, John Bent (Debugle) <notifications@debugle.com> wrote:


  Emails/html
|
|  --- Write ABOVE THIS LINE to reply ---
John Bent posted a new comment on omengib :
 http://tekinged.com/aw/m/mengib.htmI think adding an o- prefix in front of verbs often makes an action noun. Aleks, confirm? So omengib is like the act of plucking. View this on DebugleStop receiving email notifications about this item.  |

  |

**Comment by johnbent** [comment]
johnbent@gmail.com replied, <br><br>Yeah, I think almost all 'me-' verbs have an 'o-' prefix action noun variant.  I always think about going into search and doing different Palau specific 'fuzzy' matches.  Like if someone searches for 'mlik,' we'll be smart enough to recommend mlil. And uluusekool matches ousekool and this action noun thing, etc.

**Comment by johnbent** [comment]
palau371@gmail.com replied, <br><br><p>confirm the thought about action nouns.</p><p><br></p>

**Comment by johnbent** [comment]
belausim@gmail.com replied, <br><br>mengib, omengib  also means detach, detachment

**Comment by johnbent** [comment]
toninewton54@yahoo.com replied, <br><br>In the Bible I think it's talking about sowing & reaping. Â A person will reap whatever he sows.reward or punishment.
Emails/html
|
|  --- Write ABOVE THIS LINE to reply ---
Simeon Adelbai posted a new comment on omengib :
 mengib, omengib also means detach, detachment View this on DebugleStop receiving email notifications about this item.  |

  |

**Comment by johnbent** [comment]
palau371@gmail.com replied, <br><br><p>John, can you help me to make a correct eng for OMENGIB? then i will be ready to add it and to close this item.</p>

**Comment by johnbent** [comment]
omengib - n.act. - action of plucking (fruit, etc)

**Comment by smith-371** [comment]
AUTOPARSE
w omengib n.act. action of plucking (fruit, etc)
l mengib omengib

**Comment by johnbent** [comment]
Thanks @smith-371 ! Three small things for next time:
1. You don't need to create a new issue; just add the comments here
2. Please also add the 'ready for import' label
3. Please just use plain formatting for the autoparse comment

**Comment by johnbent** [comment]
Oh, the problem with your comment was you added '#' at the front of the lines. Please don't do that in the future. Just do them normal.

**Comment by johnbent** [comment]
Awesome job adding the link line!

**Comment by johnbent** [comment]
![image](https://user-images.githubusercontent.com/2047294/196524296-023da013-52be-450d-a567-0a2babc3920f.png)

Cool. It worked.

**Comment by smith-371** [comment]
> Thanks @smith-371 ! Three small things for next time:
> 
> 1. You don't need to create a new issue; just add the comments here
> 2. Please also add the 'ready for import' label
> 3. Please just use plain formatting for the autoparse comment

i couldn't find the lable 'ready for import', it was my first try with this option.

**Comment by smith-371** [comment]
by the way, OMENGIB pretty can have the possessive forms, like other n.act.'s
