### ISSUE TITLE
Ikesus

### ISSUE THREAD

**Issue by johnbent** [tekinged/missing#278]
Ikesus created by jimgeselbracht@yahoo.com on 2018-05-10 16:01:48

**Comment by johnbent** [comment]
jimgeselbracht@yahoo.com replied, <br><br>The word "ikesus" shows up in two songs I've found so far:Â  "Adidil eng kebesengei mak mo soiseb er a ikesus, kmlo soiseb er a ikesus el mo er a chang er a mengeremong" [Komorisang] and "Ikesus iss era desbedall ema ... " [Urung, although Bela Yukl sing different words].Â  I've learned that "i" in front of a word can add emphasis (e.g., itia) so is "ikesus" just an emphasis for "last night" (like, last night really rocked!)?

**Comment by ChrisPerrette** [comment]
This probably can be closed since this is a somewhat common construction. @johnbent

**Comment by johnbent** [comment]
Good suggestion @ChrisPerrette   

Closing
