### ISSUE TITLE
Missing: olekemet

### ISSUE THREAD

**Issue by johnbent** [tekinged/missing#305]
Missing: olekemet created by johnbent@gmail.com on 2019-10-14 21:28:24

**Comment by johnbent** [comment]
johnbent@gmail.com replied, <br><br>OLEKEMET?

Anyone know this word?  Can use in an example perhaps?

**Comment by johnbent** [comment]
johnbent@gmail.com replied, <br><br><p><span>Here is how someone explained it.</span></p><p><span>"It is an an ordinary word for restraining oneself...olekemet er a rengul or clenching&nbsp;fist....olekemet a chimal. These are two basic applications of the word. But it has been applied to other situations....like holding going to urinate or defecate. sulang"</span><br></p><p><span><br></span></p><p><span>Can anyone confirm please?</span></p>

**Comment by Gnalu** [comment]
Confirmed.

**Comment by johnbent** [comment]
AUTOPARSE 
w olekemet v.t. restrain; hold back. (usually used to indicate some form of self-control)
l olekemet olekemekem

**Comment by johnbent** [comment]
AUTOPARSE successfully AUTOPARSED; closing issue
