### ISSUE TITLE
Lemetat

### ISSUE THREAD

**Issue by johnbent** [tekinged/missing#32]
What is the meaning of lemetat please? Is it related to metat? Here is an example usage:

A dilak lemei Rechuluchel e ngak a smecher me a kmo milak er a lemetat e chemetii a ingukl el di melatk er a Rechuluchel a lak el lluut.

**Comment by Gnalu** [comment]
In that sentence, it’s old clothes full of holes in which I refer to as
‘holey’ clothes, sense of grieving for someone.

**Comment by johnbent** [comment]
So, can you add 'le' to the beginning of lots of words to make new words?

So, does lemesodel mean 'those torn things'?

**Comment by Gnalu** [comment]
Yes. For clothing: ‘ka le mei a ta era metetat me kungtir mo era mesei.
Could you please give me some old clothes that I can use to go to Tato
patch. People shortened it to lemetat.

Kalemei a tetat el kebui me kungtir. Give me a piece of leaf for my chew.

Le metat: worn out clothing.

Le mesodel a babii: pig to be portioned.

Le mechelebed: to be whooped.

**Comment by johnbent** [comment]
Thanks @Gnalu !

Aleks, what do you think? Do we need to add lemetat? Or is it really two separate words? Is it really 'le' or is it 'el' and somehow they started pronouncing it more like 'le'?

**Comment by smith-371** [comment]
le= looks like a pronoun prefix kinda Ng diak lesensei. 
almost any word can attach it, so i guess we have no possibility to add them all.

**Comment by smith-371** [comment]
A dilak lemei Rechuluchel e ngak a smecher me a kmo milak er a lemetat e chemetii a ingukl el di melatk er a Rechuluchel a lak el lluut. - what does all this mean?

**Comment by Gnalu** [comment]
If Rechuluchel never comes, I’m sick so I will wrap myself in old clothes
and sleep close to the cooking stove and think of Rechuluchel if he doesn’t
return.

**Comment by s-o-u-a-n-g** [comment]
The way this sentence is written makes it look like it was written before standardization of writing Palauan. We don’t need to as LE to the beginning of words since it’s a separate word. 

souang

**Comment by Gnalu** [comment]
Lemetat is referred to old clothing before they become ‘ulch’. They can
still be used to go to mesei in or sers.

Mechetengem is referred to old clothes that are not longer in use because
they longer fit but are still in good condition for hand me downs.

Belauans in the old days were best in recycling and reusing.

**Comment by Lukes-Imeyuns** [comment]
Where did you get that example sentence, John? Is it from a song? It's a
really...strange sentence.. Lol.

In my mind, it's "le metat" which is the pronunciation of "el metat." This
happens in a lot of cases where we SAY "le" before a verb but to write it
in the current format, it'll be "el _____."

"Ka bilii er tial bibrurk el buroski e ngii di lak le metat e ng kora
mechetong"
"Tia water proof meng diak le metat"
"Tial diu er ngak el oyeng el meral ngii di lak le metat a omerkolek"

The above are how we say it but again, it's just the pronunciation of "el
metat."

With regards to old clothes, I personally have never heard "lemetat" for
them. I have, however, used and heard people use "kermetat" for old
clothes, rags, or even like an old car and other items. Sometimes "teletat"
is used.

Another word I've heard is "mechetum" to refer to one's old clothes. This
comes from "mechut" and in this form (mechetum), it refers to old items due
to the person's use. Ex:  1) For clothes: Ng dimlak ngai oidellek me le mei
a tara mechetum me kuubail er ngii. 2) Other things: Tia mechetum el diak
mobang el omsang a chad le ke bai motuub.

J

**Comment by johnbent** [comment]
Hey Lukes,

That sentence is from the bottom of page 177 in this book: https://tekinged.com/misc/pdfs/cheldecheduch_v2.pdf.

**Comment by johnbent** [comment]
Thanks @JimGeselbracht . I'm not as familiar with Josephs as I should be. I read the original a few decades ago but haven't read the new ones. I should! I did just search the index in the two new grammar books and couldn't find this. Do you know whether this is discussed in the new grammar books and, if so, where?
https://tekinged.com/books/handbook1.php
https://tekinged.com/books/handbook2.php

I did find something like this in the old grammar book:
![image](https://user-images.githubusercontent.com/2047294/195118220-0e4e3ac2-2d8b-4330-a6ff-8dc644133640.png)
https://tekinged.com/books/75josephs.php

Looks like I should add 'le-' as an affix and it will appear in this list:
https://tekinged.com/show_words.php?lookup=affix

**Comment by johnbent** [comment]
![image](https://user-images.githubusercontent.com/2047294/195144063-c94f02ef-505d-4ae9-89f2-9677f605991b.png)
Found it.

**Comment by johnbent** [comment]
Closing so we can handle in #358
