### ISSUE TITLE
Toketa(ng)

### ISSUE THREAD

**Issue by johnbent** [tekinged/missing#332]
Toketa(ng) created by jimgeselbracht@yahoo.com on 2021-05-07 12:37:32

**Comment by johnbent** [comment]
jimgeselbracht@yahoo.com replied, <br><br>The song Nangaraku Sabisi has a verse containing the phrase "kchebuul e di mengeuid er a renguk / a klisichek a toketa."  Yoichi Rengiil and I were working through this lyric yesterday, listening to a recording by Halley, which confirmed the lyric.  While I had originally thought this was a contracted form of  "a klisichek a te oketa." [where "te oketa" is referring to my misery and confusion as each of my strengths].  Yoichi didn't think that made sense and suggested instead that it should be toketang, which he said was from oltak.  Based on his description, it sounds like this would be v.inch (inchoative) for oltak.  The sense of the phrase would be that while "woe is me," my strengths are now "coming on board," returning to me.  Does toketa(ng) make sense as v.inch for oltak?

**Comment by johnbent** [comment]
jlukesemiwo@gmail.com replied, <br><br>Hey Jim!

Could you complete the sentence with the word please?

**Comment by johnbent** [comment]
jimgeselbracht@yahoo.com replied, <br><br>Bechesei ke mle ngelbatel a / tonget a uldesuel ma / kchebuul e di mengeuid er a renguk  a / klisichek a toketang

**Comment by johnbent** [comment]
mngiruchelbad@gmail.com replied, <br><br>Toketang:meleketek: building up, rising up.

**Comment by johnbent** [comment]
jimgeselbracht@yahoo.com replied, <br><br>Thanks Mar

Sent from Yahoo Mail on Android

**Comment by johnbent** [comment]
So this one is almost ready for the magic. It will be something like:
w meleketek v.i. xx --toketang v.inch. 

So it is a form of meleketek which means starting to build up.

Two questions before this is ready for import:
1. Mar (and others), is there also a toketung form? 
2. Others (not Mar), can anyone confirm this please?

**Comment by Gnalu** [comment]
I have heard (totekngang)

Eiaia, tia a ko er a kma el totekngang el mocha blai. ( Oh, this is taking shape into a house,

**Comment by Lukes-Imeyuns** [comment]
There's no "toketung" form.

I'm not certain about the "starting to" part because when we say "ng kora
kmal toketang a blai," it's at a stage where a lot of work has been done,
maybe like halfway done or even later..

But if you mean that like the English "It's starting to look complete" or
something like that..then it's good. As long as it's not referring to THE
very beginning of meleketekt...

**Comment by Gnalu** [comment]
Lukes, kamotuu a mengane er kau eh kei (totekngang) ng diak el toketang, tia kora otto er a delboes (teketak) haha. smh

**Comment by Gnalu** [comment]
After much deliberation, this is actually ( te oketa) and saying it would be (toketa) which is already in Tek.com. Langsu, Brosive, your take...
langsu

**Comment by johnbent** [comment]
AUTOPARSE
w meleketek v.i. xx --toketang v.inch.
