### ISSUE TITLE
Beberotel

### ISSUE THREAD

**Issue by johnbent** [tekinged/missing#344]
Beberotel created by jimgeselbracht@yahoo.com on 2021-09-13 14:08:39

**Comment by johnbent** [comment]
jimgeselbracht@yahoo.com replied, <br><br>In the song "Yasasii el di mla Desik," composed by Emau Recheungel, the singer explains:  "Meng saisiyo re kid e ochedengchei / di kora beberotel ma / bedenged el ngara yamiyo e / dimlak kisa sungata" [And so at our onset, sweetheart / we just kind of kept it hidden and so / our bodies on the dark night / and I couldn’t even see a silhouette].  Beberotel is a reduplication of berotel.  Yoichi Rengiil explained to me the difference between berotel and beberotel:  Berotel is just a one-time thing, you omart, you cover whereas beberotel is more of a perpetual thing.  You do it today, you do it tomorrow, and you do it the day after tomorrow.

**Comment by Gnalu** [comment]
confirmed.

**Comment by johnbent** [comment]
AUTOPARSE
w omart v.i. xx --beberotel v.a.s.redup.
