### ISSUE TITLE
TONARI

### ISSUE THREAD

**Issue by ChrisPerrette** [tekinged/missing#350]
I believe <i>tonari</i> is a borrowed Japanese word meaning something like neighbor, neighborhood, or neighboring.

Example from an <i>Chedaol Biblia</i>:
“Me tirike el tonari er ngii me a remilsa er a dirk lekosiki, a dilu el kmo…” (Johanes 9:8)
“And his neighbors and they who had seen him when he was still a beggar said…” (John 9:8)

The more commonly used <i>Chedaol Biblia</i> uses a more wordy phrase:
“Me itia e tirka el ble lekaiuekeed a blirir me a rechad el milsang er a ngar a mong el di olengetngit a ngera er a rechad a uleker el kmo…” (Johanes 9:8)
“Therefore those whose houses were near to his and they who had seen him in the past continually begging things from people asked…” (John 9:8)

Sometimes the word <i>neighbor</i> is translated as <i>a ngar er a bita er ngii</i>.

Is this something that could be a candidate for addition?

**Comment by johnbent** [comment]
Looks good to me. https://japanesetest4you.com/flashcard/learn-jlpt-n5-vocabulary-%E9%9A%A3-tonari/ confirms that tonari can mean neighbor. When it is ready for the auto parsing, it will be something like:
[magic word]
w -o J -b tonari n. neighbor.

Souang, Lukes, Ulang: can any of you confirm that tonari is word Palauans use (or used to)? 

Chris, kaiuekeed is in already as is 'le'. We do not have 'le-' as a prefix but maybe that's OK.

**Comment by Gnalu** [comment]
Yes, confirmed. tonari-neighbor.

**Comment by ChrisPerrette** [comment]
Josephs lists <i>le</i>- and <i>l</i>- as reduced variants of <i>lo</i>- or <i>lu</i>-. Most Palauans just spell it separately, though, it seems. Josephs gives, for example, "A ngelekek a dirkak lebo lungil el smecher." Another from Josephs says, "A babier el lebla lebo lemerek er ngii a Toki a kmal ungil." Maybe these variants could be added as prefixes.

**Comment by ChrisPerrette** [comment]
My wife says she has heard of <i>tonari</i> but does not know its meaning. Also tekinged.com already has <i>tonari</i> in the example texts.

**Comment by ChrisPerrette** [comment]
AUTOPARSE
w -o J -b tonari tonari n. neighbor.

**Comment by johnbent** [comment]
Thanks @ChrisPerrette ! When we know the origin word (in this case the same exact word tonari), we can add that also with a -b flag. So I edited your comment just a bit to add that.

Also, still need to add the label. One sec. Let me make instructions for that.

**Comment by johnbent** [comment]
Chris, please check out the instructions here and let me know if they work for you:
https://github.com/tekinged/missing/discussions/348

Thanks for joining our committee!

**Comment by johnbent** [comment]
Chris, I added you as a contributor and a committee member: https://tekinged.com/about.php#

**Comment by ChrisPerrette** [comment]
Thank you

**Comment by johnbent** [comment]
![image](https://user-images.githubusercontent.com/2047294/196497210-484d134d-374d-424d-84b4-b0ecd7de4ea5.png)
It worked! Thanks @ChrisPerrette

**Comment by ChrisPerrette** [comment]
Awesome! I am glad there are already example sentences.
