### ISSUE TITLE
AUTOPARSE

### ISSUE THREAD

**Issue by smith-371** [tekinged/missing#352]
AUTOPARSE
# w omengib n.act. action of plucking (fruit, etc)
# l mengib omengib

_Originally posted by @smith-371 in https://github.com/tekinged/missing/issues/239#issuecomment-1282859198_

**Comment by johnbent** [comment]
No need to create a new issue. Just a comment in existing issues.

**Comment by smith-371** [comment]
i couldn't find out how to label it...

**Comment by johnbent** [comment]
Instructions can be found here: #348 . Please take a look and let me know if you have questions.
