### ISSUE TITLE
Words Needing Linking

### ISSUE THREAD

**Issue by smith-371** [tekinged/missing#353]
AUTOPARSE
l cheroll ulemcheroll
l delebaob melebaob

**Comment by smith-371** [comment]
should I create another new issue for next word pairs, or is it possible to run it from this issue?

**Comment by johnbent** [comment]
![image](https://user-images.githubusercontent.com/2047294/196541238-243f945c-3277-4d37-b9a3-7a6803db4d23.png)
![image](https://user-images.githubusercontent.com/2047294/196541366-ca73cb41-65a5-45f5-887e-d1b6240254d2.png)

Awesome, it worked.

**Comment by johnbent** [comment]
> 

New issue please.
