### ISSUE TITLE
Misplaced Expression

### ISSUE THREAD

**Issue by ChrisPerrette** [tekinged/missing#355]
This phrase seems like it does not belong under <i>eou</i>.

![image](https://user-images.githubusercontent.com/116015127/196588570-7bb1d555-d2dd-47d9-9821-da8a279dcb06.png)

**Comment by Lukes-Imeyuns** [comment]
Agreed.

**Comment by johnbent** [comment]
Fixed.

**Comment by johnbent** [comment]
Thanks @ChrisPerrette and @Lukes-Imeyuns !
