### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by johnbent** [tekinged/missing#357]
![image](https://user-images.githubusercontent.com/2047294/196598596-acab11bb-3cc9-4ffa-9d2b-e875bec77dbe.jpeg)

**Comment by johnbent** [comment]
Our host changed the MySQL version and for some reason MySQL changed the legal markers for word boundaries. Annoying. I'll fix.

**Comment by ChrisPerrette** [comment]
This happens for me, too. Often when I click the example text option.

**Comment by johnbent** [comment]
OK. Fixed closing.
