### ISSUE TITLE
Bug2

### ISSUE THREAD

**Issue by johnbent** [tekinged/missing#359]
![image](https://user-images.githubusercontent.com/2047294/196753770-8c7f4d12-0eb2-433d-b029-91a03691f080.jpeg)

Thanks @Gnalu for reporting!

**Comment by johnbent** [comment]
@Gnalu , I maybe fixed this. Can you try again and let me know if it works for you without seeing any errors?

Thanks for reporting this!

**Comment by johnbent** [comment]
@Gnalu , I think this is fixed. I'm closing this. Please let me know if you encounter future problems!

**Comment by Gnalu** [comment]
working, awesome, langsu ochedengei.
