### ISSUE TITLE
UNTENDAI

### ISSUE THREAD

**Issue by johnbent** [tekinged/missing#361]
Ak ngar a untendai e kemui a mo er uriul. I'm in the passenger seat and you all are in the back.

@Gnalu reported this to me. Can anyone confirm? It's a bit confusing though since untendai in Japanese actually means driver's seat.

If this is passenger seat, what is driver's seat in Palauan?

**Comment by smith-371** [comment]
in Japanese UNTENDAI is driver's seat:
https://www.nihongomaster.com/japanese/dictionary/word/64048/untendai-運転台-うんてんだい

**Comment by Lukes-Imeyuns** [comment]
One of those Japanese words adopted...and modified...

Today, when we use it we are referring to the FRONT passenger seat...seat
next to driver..

**Comment by johnbent** [comment]
AUTOPARSE
w -o J -b untendai untendai n. passenger seat.
e Ak ngar a untendai e kemiu a mo er uriul. --I'm in the passenger seat and you all are in the back.

**Comment by smith-371** [comment]
there is a typo in the example: KEMIU, not kemui.

**Comment by johnbent** [comment]
> 

Fixed the KEMIU typo. Can you approve please so the script can import it?
