### ISSUE TITLE
SKOBETANG

### ISSUE THREAD

**Issue by johnbent** [tekinged/missing#362]
A John a blechoel el loba a bosel el _skobetang_ el mei el me omoes.

Can anyone offer a definition please? And maybe what part of speech it is? And is it related to any other words?

**Comment by Gnalu** [comment]
Escopeta: derived from Spanish meaning shotgun.

**Comment by johnbent** [comment]
AUTOPARSE
w -o S -b escopeta skobetang n. shotgun.

**Comment by ChrisPerrette** [comment]
Looks good. Not sure how to “like” this one.

**Comment by johnbent** [comment]
In the auto-parse comment, there should be a smiley face emoji. Click on it and you'll see some 'reactions'. One is a thumbs-up. Please click it. Thanks!

**Comment by johnbent** [comment]
I just gave it a thumbs-up so just add yours please.

**Comment by johnbent** [comment]
AUTOPARSE successfully AUTOPARSED; closing issue

**Comment by johnbent** [comment]
AUTOPARSE successfully AUTOPARSED; closing issue

**Comment by johnbent** [comment]
AUTOPARSE successfully AUTOPARSED; closing issue

**Comment by johnbent** [comment]
AUTOPARSE successfully AUTOPARSED; closing issue

**Comment by johnbent** [comment]
AUTOPARSE successfully AUTOPARSED; closing issue
