### ISSUE TITLE
BUG: Variants are not always highlighted in search

### ISSUE THREAD

**Issue by johnbent** [tekinged/missing#370]
Example: CHAKKAI is not highlighted

<img width="852" alt="image" src="https://user-images.githubusercontent.com/2047294/197317247-6562cf3c-f1ae-4532-8f34-39ddf04ad3c3.png">

**Comment by johnbent** [comment]
The problem was that that highlight is using a regex that didn't include '/' as a front boundary. Fixed.

<img width="667" alt="image" src="https://user-images.githubusercontent.com/2047294/197317280-4d0f9e25-b65f-40bb-a6f8-bb1227927098.png">

FYI @ChrisPerrette , thanks for reporting this. This is fixed now.

**Comment by ChrisPerrette** [comment]
Hooray!
