### ISSUE TITLE
FEATURE REQUEST: When hovering over a clickable word in a Palauan definition, show a quickview tooltip of the word.

### ISSUE THREAD

**Issue by ChrisPerrette** [tekinged/missing#376]
Instead of having to navigate to a new webpage for every word, when hovering the cursor over a Palauan word in a Palauan definition or in the See Also or Synonyms area, show a tooltip of the word, origin, pos, English def, and Palauan def. If the user wants more details, he can click the word.

Ideas:
Use smaller print so it does not take up the whole screen.
Allow it to display multiple entries for homonyms.

**Comment by johnbent** [comment]
Great idea. Don't know how hard this would be to do. I'll look into it.

Nice job following the convention to use 'FEATURE REQUEST' in the title.

**Comment by johnbent** [comment]
This would be easy to do when we build the page by going through every word and doing a query and populating a tooltip for each word. That would be brutal slow to build the page though and would basically destroy the user experience. So we need to populate the tooltip at runtime which is harder.

[This page](https://stackoverflow.com/questions/45157767/javascript-tooltip-with-run-time-data) discusses a similar requirement. 

[This page](https://stackoverflow.com/questions/7993949/how-to-generate-dynamic-tooltips-with-data-from-mysql-using-php) is someone asking the same question but not getting a good answer unfortunately.

[This page](https://makitweb.com/dynamically-show-data-in-the-tooltip-using-ajax/) seems to be the solution but using some tools I'm not currently super familiar with.

**Comment by ChrisPerrette** [comment]
Nice fade-in effect and shadow

**Comment by johnbent** [comment]
Ok. Super close now. I did all the hard parts that I didn't know how to do. The remaining should be straight-forward.

**Comment by johnbent** [comment]
<img width="405" alt="image" src="https://user-images.githubusercontent.com/2047294/197926195-bf0b5ca6-1042-43d8-a7fa-859b1ad1723a.png">

![image](https://user-images.githubusercontent.com/2047294/197926209-69b1117f-899b-4704-a31f-f470abf590f8.png)

BOOM! Thanks @ChrisPerrette . This is pretty awesome. Mostly I'm on my phone so I won't appreciate it but it's definitely awesome when on computer. I think this is done so I'm closing it myself. But please re-open if it doesn't work for you or if you have a preference for doing it somehow differently.

**Comment by johnbent** [comment]
Oh, yeah, works for homonyms too:

<img width="414" alt="image" src="https://user-images.githubusercontent.com/2047294/197926723-704fce85-6dc1-41bb-b932-33c23b09ebff.png">

**Comment by johnbent** [comment]
<img width="374" alt="image" src="https://user-images.githubusercontent.com/2047294/197926855-02623eeb-db12-406a-9922-8cca0dd67bb7.png">

Hmm, I do wish I could make it wider though.....

**Comment by ChrisPerrette** [comment]
It looks awesome, and it is definitely what I pictured! It even works on my phone if I long-touch the word and tap out of the context menu that appears. Definitely one of the most useful features in my opinion.

One suggestion, can homonyms be ordered the same way search results are ordered? That way, for example, the state verb <i>diak</i> can precede the derivative possessed noun <i>diak</i>.

**Comment by johnbent** [comment]
Figured out how to change the width.

Fixed the order. Was scared it would be hard but turned out to be super easy.

**Comment by johnbent** [comment]
Do you have an iphone? On my iphone, it looks garbage in Safari because every palauan word is doing a new line. But it looks good in chrome. And the long-touch works for me too; neat! 

Shoot, looks like I broke something in IOS/Safari. Ugh.

**Comment by johnbent** [comment]
Nevermind. Looks fine in IOS/Safari now. I followed instructions to wipe history but it appears that it was somehow cached. All good!

**Comment by ChrisPerrette** [comment]
I have an Android phone, and I use Google Chrome. I had to clear my cache on Chrome to see some of the changes you mentioned.
