### ISSUE TITLE
BIDABT

### ISSUE THREAD

**Issue by johnbent** [tekinged/missing#396]
Portugese man-of-war?
Jellyfish?

![image](https://user-images.githubusercontent.com/2047294/211667552-fe673ccd-0c71-4f20-b68e-7b12b56eeb3a.png)

**Comment by smith-371** [comment]
we already have it as BIDABD. do you wanna improve its meaning?

**Comment by Gnalu** [comment]
Thats the right spelling bd together sounds out ‘t’.

**Comment by johnbent** [comment]
My bad. Closing.
