### ISSUE TITLE
Create new linkings

### ISSUE THREAD

**Issue by johnbent** [tekinged/missing#404]
l omturech uturech
l ramek omekramek
l llechukl meluches
l mesei meselech omeklochel
l olemedem melemedem
l kliangel siangel
l ulellitel melilt
l cheleatel mengaet
l ormotel meremet
l ortangel merot
l chuib olechib
l cheroll ulemcheroll
l duob oldob
l duoseb oldoseb
l kmes olekes
l ruames rames

**Comment by johnbent** [comment]
FYI @smith-371 . I think this is the best way to do this.

**Comment by johnbent** [comment]
Done.
![image](https://user-images.githubusercontent.com/2047294/221274472-604684c8-720c-41c6-825e-5ac0e68215c6.png)

**Comment by smith-371** [comment]
should I create another issue for the next time?

**Comment by johnbent** [comment]
Yes please create a new issue next time instead of opening this closed one.

Thanks for contributing these!
