### ISSUE TITLE
TEKINGED doesn't work

### ISSUE THREAD

**Issue by smith-371** [tekinged/missing#411]
HTTP ERROR 500

**Comment by ChrisPerrette** [comment]
I have the same issue.

**Comment by johnbent** [comment]
Yeah, annoying. They constantly update the version of PHP and PHP is some horrible language that constantly breaks backwards compatibility.

To exacerbate things, my company disabled outgoing ssh from my laptop so I have to figure out some other way to fix it.

The other way to fix it would be to change the hosting plan from _shared_ which costs about $150 / year and I'm happy to pay myself to _dedicated_ which costs about $1500 / year and we'd have to find some sponsorship to pay for that.

**Comment by smith-371** [comment]
does your company control your laptop or the network connection you use at home?

**Comment by johnbent** [comment]
Laptop. It’s technically their laptop.

**Comment by smith-371** [comment]
I don't know prices in US and what technical requirements for work on our DB are, but it seems another laptop may be cheeper, than 1500$ a year. maybe some preowned laptop is possible.

**Comment by ChrisPerrette** [comment]
Is there a fund that can be donated to for the site? I know I would give some.

**Comment by johnbent** [comment]
For the most part I’m very happy to find it myself. Just busy now. I think
my iPad can ssh and I have a keyboard on it so that should work pretty
well. Just haven’t had a chance to check yet. Apologies. I’ll get it back
up soon. Thanks though Chris.

**Comment by smith-371** [comment]
for me now it is technically difficult to drop you some dollars from Russia. but I will be happy to share some ideas could help us.

**Comment by johnbent** [comment]
@smith-371 and @ChrisPerrette , I think it's fixed now. Please check and close this ticket if it works for you again. I just restored it to use the old version of php. I do need to upgrade php again but at least it's working now. I'll try not to let it break again and try to fix it more quickly when it does. Sorry about that.

**Comment by johnbent** [comment]
By the way, we should have a facebook group or a mailing list or something so we can send announcements out to folks. I wonder how many folks saw it was broken and gave up trying to access it. It would be good if there was some way to let those folks know that it is working again.

**Comment by johnbent** [comment]
Turns out that we do have a facebook group: https://www.facebook.com/groups/tekinged. I'd forgotten about it. I posted a message there saying that tekinged is fixed now.

**Comment by smith-371** [comment]
yes, it pretty works now)
