### ISSUE TITLE
Chembrungel

### ISSUE THREAD

**Issue by johnbent** [tekinged/missing#449]
I always hear chembrungel but both the Joseph's and the Klechibelau dictionaries don't have a b. They just have chemrungel. 

Can anyone confirm that people say Chembrungel? We could add as variant. Additionally, if multiple of you are convinced that there is no chemrungel, instead of adding a variant, we can just change the spelling.

**Comment by Gnalu** [comment]
Chemrungel.

**Comment by Lukes-Imeyuns** [comment]
I always have a "b" in there... 😅

**Comment by ChrisPerrette** [comment]
It seems like it might be a slight pronunciation difference due to _m_ and _b_ being close in pronunciation, especially followed by the Palauan _r_. Like people hear the _b_ sound, but it is an auditory illusion. Then again, Palauan has many variations, so it could be that, as well.

**Comment by Lukes-Imeyuns** [comment]
A similar word is cherembrum/cheremrum.

**Comment by johnbent** [comment]
Maybe also mengeremrum and churemrum?

**Comment by Lukes-Imeyuns** [comment]
Yes. That too.

**Comment by johnbent** [comment]
It's funny. Charl and Allen and I had a big long discussion about it
because Allen said it has no B in it. So we asked him to say the word and
it sounds like there is a B in it to both Charl and I when he says it at
normal speed. But when he says it very slowly one syllable at a time, there
is no B sound. Weird.

**Comment by Lukes-Imeyuns** [comment]
Kind of like some words that sound like there's an "a" at the end. It
usually just happens when the word ends with an "L" like Ngcheangel,
lmangel, chelbangel, beldakl, etc.

I actually never realized this until Troy pointed it out.

**Comment by johnbent** [comment]
I'm going to close this thread. Thx for the discussion!
