### ISSUE TITLE
MEDAKT A DELEB

### ISSUE THREAD

**Issue by johnbent** [tekinged/missing#460]
This is a type of banana. Can anyone confirm? Can anyone upload a picture? Provide the latin name?

**Comment by Gnalu** [comment]
Is that the king green one looks like ‘orsul a kaming’? Goats horn very
curvy  inward?

**Comment by johnbent** [comment]
Not sure about the details but at least we can confirm it is a banana. I'll close this and hopefully we can get a picture.
