### ISSUE TITLE
Tiem

### ISSUE THREAD

**Issue by JimGeselbracht** [tekinged/missing#484]
In the 1977 song "Belochel," Blas Sbal used the word "tiem" (also spelled "tiyem") in the phrase "ak mo smiik a tiem el reng."  I see that "tiem" is also in an example sentence in tekinged with the phrase "... e nguu a tiem el cheluch el ngar er a chelsel a ulengchidel."  What is "tiem"?

**Comment by Gnalu** [comment]
Tiem is another word for chilt, special made topical lotion.

**Comment by JimGeselbracht** [comment]
Thanks Mar.  I see it now.  It is n.poss.2s from taiu, which tekinged defines as:  cosmetic/hair oil; pomade

**Comment by johnbent** [comment]
Closing.
