### ISSUE TITLE
ma da 

### ISSUE THREAD

**Issue by JimGeselbracht** [tekinged/missing#492]
What is the meaning when the word "da" is added in phrases like "ma da bo dekebii," "A da mei me dorael e Sarang," "Me a da mluut el ngoikak," etc.  What part of speech is this?

**Comment by johnbent** [comment]
Maybe it comes from ADANG and the NG is dropped?
https://tekinged.com/?lookup=adang&direction=pe

**Comment by Gnalu** [comment]
Bent nailed it. It is like an agreement without an option to say no. :-)

**Comment by JimGeselbracht** [comment]
Thanks, that makes sense.  So it should be written "me ada dorael"

**Comment by Gnalu** [comment]
Yes, exactly.
