### ISSUE TITLE
Scorpion

### ISSUE THREAD

**Issue by johnbent** [tekinged/missing#502]
![image](https://github.com/tekinged/missing/assets/2047294/e6bcda6c-1aa5-4282-b012-256108141940)

Is this a local bug or did it come in an Amazon package or something? If local, what is name? I couldn't find scorpion insect in the dictionary. 

Seen in Chol.

**Comment by johnbent** [comment]
There is this:

iusbeluu	n.	scorpion .
iusbeluu  a  ta  er  a  bedengel  a  charm  er  a  beluu  el  ko  er  a  ius.  A  iusbeluu  a  charm;  ng  kmal mekekerei  el  charm.  Kede  metik  er  a  beluu.  Ng  ko  er  a  mechedelekelek  a  bedengel.  Ng diak  el  kall.

But it doesn't look like a crocodile.

**Comment by Gnalu** [comment]
Iusbekuu is a scorpion and he/she is local.
