### ISSUE TITLE
sibrir

### ISSUE THREAD

**Issue by JimGeselbracht** [tekinged/missing#510]
In the song "Tachukall" is the line "Le ke sibrir a remesiich," with sibrir being v.pf.3p meaning "to serve them."  Sibrir also shows up in 3 example sentences in tekinged.  My question is what verb is sibrir derived from?  Sibai is a noun.  Ousibai is defined as "enslave; make a slave of; treat as a servant," and so is from the perspective of the person who is being served, not from the person doing the serving.  Does ousibai have a broader meaning than what is in tekinged?

**Comment by Gnalu** [comment]
Sibai.
 Mesiou from omesiou. Serve.

**Comment by johnbent** [comment]
Actually, I think that sibrir is the n.poss.3p of sibai and not a
perfective form of mesiou.
