### ISSUE TITLE
Chemotang

### ISSUE THREAD

**Issue by JimGeselbracht** [tekinged/missing#516]
Ymesei Ezekiel, in his 1968 song "Sils a Mochu Kebesengei," uses the line "tiai a rengum el di chemotang."  I was told that chemotang (which looks v.inch) means to illuminate something, make it apparent, etc., or in this case, "this heart of yours has just shown its true colors."  Chemotang is also used in a number of examples currently in tekinged, and pretty much means to highlight something that had been hidden.  What is the root verb?

**Comment by Gnalu** [comment]
Chemolt: chemotang: cholecholt: ullecholt:

**Comment by johnbent** [comment]
We already have ochotall as the v.a.s. of olecholt so this looks like 'v.s.inch' of chemolt. This is a good one to request verification from PLC. Also, is there another word chemotung which would be the 'v.s.pred' form of chemolt?

**Comment by Gnalu** [comment]
Chemolt: chemotang: feelings/ emotions
Chuob: things appearing
Olecholt: being shown as in observed
Duum: person appearing

**Comment by JimGeselbracht** [comment]
Thanks Mar - olecholt makes total sense.  
    On Thursday, August 8, 2024 at 04:44:34 PM PDT, Gnalu ***@***.***> wrote:  
 
 

Chemolt: chemotang: feelings/ emotions
Chuob: things appearing
Olecholt: being shown as in observed
Duum: person appearing

**Comment by Lukes-Imeyuns** [comment]
@ John - there is no chemotung, just chemotang

**Comment by johnbent** [comment]
@palaulanguage.2@gmail.com, can you confirm that _chemotang_ is v.s.inch. of _chemolt_ please?

**Comment by johnbent** [comment]
Confirmed by PLC. Now added.

<img width="1077" alt="image" src="https://github.com/user-attachments/assets/47c0a4e2-8604-47bb-8320-204e9239f79a">
