### ISSUE TITLE
Link mengetakl and chetakl

### ISSUE THREAD

**Issue by johnbent** [tekinged/missing#529]

**Comment by johnbent** [comment]
Also chiukl and chikl

**Comment by Gnalu** [comment]
Chiukl: two meanings: one is song and to be woven.
Chikl: neck:chklek(my neck), chiklel:his/her neck. Chiklir:their
voices/their necks or their voice, same for the other ones, voice or neck.

Mengetakl: trolling/leading/persuading.

Chetakl: tools for fishing (trolling).

Chachetakl: for persons, persuaded group of people doing something, good or
bad.

**Comment by Lukes-Imeyuns** [comment]
Agree with Mar on the neck, voices, and fishing related definitions.

As for to be woven, don't you mean CHEUIKL, Mar?

CHEUIKL - basket to be woven
CHUKLEK
CHUKLEL
Etc

**Comment by Gnalu** [comment]
Thank Lukes, that’s it.
