### ISSUE TITLE
Possessed form of TELITUR

### ISSUE THREAD

**Issue by johnbent** [tekinged/missing#534]
Are there possessed forms of TELITUR? 

For example, a possessed form of BLAI is BLIL, MLAI is MLIL, BOES is BOSEL, RUBAK is RUBEKNGEL, DAOB is DEBEL, etc.

What about TELITUR?

**Comment by Gnalu** [comment]
Metitur
Telitur
Only

**Comment by johnbent** [comment]
So you say something like, "Ng checherd a renguk er a telitur er kau"?

**Comment by Lukes-Imeyuns** [comment]
Yes. We just used ngii, kau, tir, etc to show the possessive form.
