### ISSUE TITLE
klausurui

### ISSUE THREAD

**Issue by johnbent** [tekinged/missing#536]
I saw this word being used. Is it 'lying to each other' from ousurui? Is it commonly used or did someone just make up a word?

**Comment by Gnalu** [comment]
Ousurui:
Te ulusurui
Klausurui.

😊

**Comment by Lukes-Imeyuns** [comment]
It is in fact a word that is commonly used. Klausurui is the noun of
ousurui. Also, though one IS lying when they "ousurui" I still think
"cheating" is another good definition.

**Comment by johnbent** [comment]
Thanks. Added. Closing.
