### ISSUE TITLE
KANGURU

### ISSUE THREAD

**Issue by johnbent** [tekinged/missing#6]
Someone asked me to add KANGURU for kangaroo. This seems silly. I don't think we should add every English word with a Palauan pronunciation and spelling. If folks think otherwise, please let me know. But otherwise I am not planning to add this.

**Comment by s-o-u-a-n-g** [comment]
Correct. It is not necessary to add every English word used when a Palauan speaker code-switches. No need to add kampiurer, and cheirtaim, for example.

**Comment by Gnalu** [comment]
I was reading it as Japanese second to Souang and I was reading Cheirtaem
cheritem. Belauan is going to be lost soon enough aye yi yi.

**Comment by Lukes-Imeyuns** [comment]
LOLOL @ kampiurer ma cheirtaem.

Should we add other things like "obaho" (overhaul)?

Agreed. It's not necessary.

**Comment by smith-371** [comment]
hm... obaho and raichong are not so obvious, like kanguru

**Comment by s-o-u-a-n-g** [comment]
"obvious" is subjective.

**Comment by johnbent** [comment]
@s-o-u-a-n-g , it's a great point that subjective is obvious. I think @smith-371's comment contained an implied "to me". And, to me, obaho and raichong are also not so obvious. And maybe even words like cheirtaem which are heavily used should be added. kampiurer is 'computer' I guess? I'm still of the strong opinion that kanguru shouldn't be added. It's (to me) very obvious AND it's not a frequently used word at all.

**Comment by Gnalu** [comment]
There’s Raichong in palauan example text with the English version so it’s
covered.

**Comment by johnbent** [comment]
AUTOPARSE
w -o E -b overhaul obaho n. overhaul.

**Comment by johnbent** [comment]
I am gonna add obaho because that's not obvious to either Aleks or I. Not gonna add kangeroo though. Thanks all!
